### PR TITLE
Roster system

### PR DESCRIPTION
**Pull request by shurwit**
# Description

This pull request adds a simple roster system to the health building block. 

## API Definitions

- **/covid19/rosters/phone/{phone}**
  - **GET**
    - **Description**: Fetches `externalID` for given `phone` number
    - **Headers**:
      - `ROKWIRE-API-KEY`: api key (required)
    - **Parameters**:
      - `phone`: string (query)
        - Phone number of user to search roster by
    - **Response**:
      - Status Codes:
        - 200 - Body: `externalID` of the roster member with the specified phone number (string)
      - Others - Check body for error message

- **/admin/rosters**
  - **GET**
    - **Description**: Fetches current roster data
    - **Headers**:
      - `Authorization`: admin ID token (required)
    - **Parameters**:
      - `{any field}`: string (query)
        - Specify the value of any of the fields in the data to filter results. You can specify as many of these as you would like
      - `sortBy`: string (query) 
        - Specify one of the fields in the data to sort results by. **Default**: lastname
      - `sortOrder`: int (query)
        - 1 (ascending), -1 (descending). **Default**: 1
      - `limit`: int (query)
        - Number of results to return. 
          **Minimum**: 1, **Maximum**:50, **Default**: 20
      - `offset`: int (query)
        - Offset for pagination. **Default**: 0
    - **Response**:
      - Status Codes:
        - 200 - Body:
        [{
          "externalID": string (required),
          "phone": string (required),
          ...
          Any other desired fields
        }]
      - Others - Check body for error message
  - POST
    - **Description**: Replaces roster with uploaded list
    - **Headers**:
      - `Authorization`: admin ID token (required)
    - **Parameters**:
      - Body: 
[{
    "externalID": string (required),
    "phone": string (required),
    ...
    Any other desired fields
}]
    - **Response**:
      - Status Codes:
        - 200 - Success/Warning message
        - Others - Check body for error message
  - PUT
    - **Description**: Updates roster with uploaded list. Adds new rows and replaces rows with matching `externalID`
    - **Headers**:
      - `Authorization`: admin ID token (required)
    - **Parameters**:
[{
    "externalID": string (required),
    "phone": string (required),
    ...
    Any other desired fields
}]
    - **Response**:
      - Status Codes:
        - 200 - Success/Warning message
        - Others - Check body for error message
  - DELETE
    - **Description**: Deletes members from roster
    - **Headers**:
      - `Authorization`: admin ID token (required)
    - **Parameters**:
      - `{any field}`: string (query)
         Specify the value of any of the fields in the data to filter results. You can specify as many of these as you would like. If none, all data will be deleted
    - **Response**:
      - Status Codes:
         - 200 - Success:
        - Others - Check body for error message

### CODE REVIEW

**Comment by mihail-varbanov** [comment]
Regarding /covid19/rosters/phone/{phone} Response Body:

1. Shouldn't we keep a single relation between phone number and external Id? In other words the response to contain a single external Id instead of a list of such?

2. Why doesn't this API return JSON content like all other Health BB APIs?

**Comment by shurwit** [comment]
> Regarding /covid19/rosters/phone/{phone} Response Body:
> 
> 1. Shouldn't we keep a single relation between phone number and external Id? In other words the response to contain a single external Id instead of a list of such?
> 2. Why doesn't this API return JSON content like all other Health BB APIs?

Hi Misho,

I have updated the endpoint to return a single externalID string and added an index to enforce uniqueness on the "phone" field. This API was repurposed from a different one within our system that was returning multiple values. I apologize for the oversight. Please let me know if the last push resolves your concerns.

**Review by petyos — APPROVED** [review]
The feature is added according to the service architecture. There are some minor isues but they will be fixed on next step

**Comment by mihail-varbanov** [comment]
Thanks @shurwit. I think that making phone unique should resolve this small inconsistency.

**Pull request merged**
